# Configurations
title:            Dialougia
longtitle:        Dialogue avec une IA
author:           Viglino
email:            jean-marc.viglino@ign.fr
description: Dialogue avec une IA
  
version:          1.0

url:              'https://viglino.github.io'
baseurl:          '/dialoguia'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: just-the-docs/just-the-docs

# Back to top link
back_to_top: false
back_to_top_text: "Haut de page"

footer_content: "Copyright &copy; 2024 - <a href=\"https://github.com/Viglino\">Jean-Marc Viglino</a> - CC-BY-NC-SA"

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
# favicon_path:     assets/favicon.ico
